# Java Maven CircleCI 2.0 configuration file
version: 2
jobs:
  build:
    docker:

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m
    
    steps:
      - checkout
      run: git submodule sync
      run: git submodule update --init
      run: mvn clean
      run: mvn package
      run: cp -R ./target/JupiterX-0.1-SNAPSHOT.jar $CIRCLE_ARTIFACTS

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "pom.xml" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      #- run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
        
      # run tests!
      - run: mvn integration-test
